const pool = require('../../shared/db/connection');
const xlsx = require('xlsx');
const backupService = require('./backup.service'); // To trigger auto-backup
const queries = require('./backup.queries');

class RestoreService {
    async parseFile(buffer, mimetype, originalName) {
        let rawData = {};
        
        if (originalName.endsWith('.xlsx')) {
            const workbook = xlsx.read(buffer, { type: 'buffer' });
            for (const sheetName of workbook.SheetNames) {
                rawData[sheetName] = xlsx.utils.sheet_to_json(workbook.Sheets[sheetName], { raw: false });
            }
        } else if (mimetype === 'text/csv' || originalName.endsWith('.csv')) {
            const workbook = xlsx.read(buffer, { type: 'buffer' });
            const sheetName = workbook.SheetNames[0];
            rawData['csv'] = xlsx.utils.sheet_to_json(workbook.Sheets[sheetName], { raw: false });
        } else {
            throw new Error('Unsupported file format.');
        }

        const firstSheet = Object.values(rawData)[0];
        if (!firstSheet || firstSheet.length === 0) {
            throw new Error('File is empty or corrupted.');
        }

        const metaRow = firstSheet[0];
        let type = 'unknown';
        let fileOwnerId = null;

        for (const val of Object.values(metaRow)) {
            if (typeof val === 'string') {
                if (val.startsWith('type=')) type = val.split('=')[1];
                if (val.startsWith('owner_id=')) fileOwnerId = val.split('=')[1];
            }
        }

        if (type === 'unknown' || !fileOwnerId) {
            throw new Error('Invalid metadata row. The file must be generated by this system.');
        }

        // Clean metadata row
        for (const sheetName of Object.keys(rawData)) {
            if (rawData[sheetName].length > 0) {
                // Determine if first row is metadata
                let hasMeta = false;
                for (const val of Object.values(rawData[sheetName][0])) {
                    if (typeof val === 'string' && val.startsWith('owner_id=')) hasMeta = true;
                }
                if (hasMeta) rawData[sheetName].shift();
            }
        }

        // If CSV, rename the generic 'csv' sheet to the backup type
        if (rawData['csv']) {
            rawData[type] = rawData['csv'];
            delete rawData['csv'];
        }

        return { type, fileOwnerId, data: rawData };
    }

    async validateRestore(parsedData, ownerId) {
        if (parsedData.fileOwnerId !== ownerId) {
            return { valid: false, message: 'CRITICAL WARNING: This backup file belongs to a completely different user account! Restore blocked.' };
        }
        
        let totalRecords = 0;
        let emptyCount = 0;
        for (const rows of Object.values(parsedData.data)) {
            totalRecords += rows.length;
            if (rows.length === 0) emptyCount++;
        }

        if (totalRecords === 0) {
            return { valid: false, message: 'File is completely empty. Restore blocked.' };
        }

        return { 
            valid: true, 
            message: `Validated successfully. Ready to restore ${totalRecords} records securely.` 
        };
    }

    async executeRestore(ownerId, type, parsedData, strategy) {
        const allowedTables = ['customers', 'products', 'product_versions', 'variants', 'sales', 'sale_items', 'attendance', 'stock'];
        
        // Backwards compatibility: map old 'flavours' sheet to 'variants'
        if (parsedData.data && parsedData.data['flavours']) {
            parsedData.data['variants'] = parsedData.data['flavours'];
            delete parsedData.data['flavours'];
        }
        
        const client = await pool.pool.connect();
        try {
            await client.query('BEGIN');

            // Snapshot active sales before restore
            const snapQ = queries.getSaleItemsSnapshot(ownerId);
            const preSalesRes = await client.query(snapQ.text, snapQ.values);
            const preSales = {};
            preSalesRes.rows.forEach(r => preSales[r.variant_id] = parseInt(r.qty));


            // Layer 3 Safeguard: Trigger silent auto-backup before wiping is removed because wipe is removed
            // Cascade wipe is removed

            // Restore engine - strictly ordered to prevent insertion foreign key violations
            const insertOrder = ['customers', 'products', 'product_versions', 'variants', 'stock', 'sales', 'sale_items', 'attendance'];
            for (const tableName of insertOrder) {
                const rows = parsedData.data[tableName];
                if (!rows || rows.length === 0) continue;
                
                if (tableName === 'stock') {
                    console.log('Skipping stock sheet to protect live stock data.');
                    continue;
                }
                
                if (!allowedTables.includes(tableName)) {
                    console.warn(`Skipping unknown sheet/table: ${tableName}`);
                    continue;
                }

                const columns = Object.keys(rows[0]).filter(k => k !== 'id' || true);
                
                let dbColumns = columns.map(c => {
                    if (tableName === 'customers' && c === 'date') return 'joined_at';
                    if (tableName === 'variants' && c === 'product_id') return 'product_version_id';
                    return c;
                });
                
                const currencyColumns = ['shake_amount', 'price_charged', 'standard_price_snap', 'vendor_price_snap', 'vendor_price'];

                for (const row of rows) {
                    const values = columns.map(col => {
                        let val = row[col] === '' ? null : row[col];
                        if (val !== null && currencyColumns.includes(col)) {
                            val = Math.round(parseFloat(val) * 100);
                        }
                        if (val === 'false' || val === 'FALSE') val = false;
                        if (val === 'true' || val === 'TRUE') val = true;
                        
                        return val;
                    });

                    // ON CONFLICT requires a unique constraint. We assume id is unique UUID.
                    if (columns.includes('id')) {
                        const query = queries.buildMergeInsertQuery(tableName, dbColumns);
                        await client.query(query, values);
                    } else {
                        const query = queries.buildStandardInsertQuery(tableName, dbColumns);
                        await client.query(query, values);
                    }
                }
            }

            // Snapshot active sales after restore
            const postSalesRes = await client.query(snapQ.text, snapQ.values);
            const postSales = {};
            postSalesRes.rows.forEach(r => postSales[r.variant_id] = parseInt(r.qty));

            // Calculate exact diff and deduct from stock
            const allVariantIds = new Set([...Object.keys(preSales), ...Object.keys(postSales)]);
            for (const variantId of allVariantIds) {
                const preQty = preSales[variantId] || 0;
                const postQty = postSales[variantId] || 0;
                const diff = postQty - preQty;
                
                if (diff !== 0) {
                    const updQ = queries.updateStockDifferential(diff, variantId, ownerId);
                    await client.query(updQ.text, updQ.values);
                }
            }

            await client.query('COMMIT');
            return { success: true, message: `Successfully restored backup using ${strategy} strategy.` };
        } catch (error) {
            await client.query('ROLLBACK');
            console.error('RESTORE ROLLBACK:', error);
            throw new Error(`Restore failed during atomic transaction. Database was instantly rolled back. Error: ${error.message}`);
        } finally {
            client.release();
        }
    }
}

module.exports = new RestoreService();
